---
- name: restart resolved
  service:
    name: systemd-resolved
    state: restarted
  become: yes
  listen: restart resolved

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
  become: yes
  listen: restart journald

- name: restart networkd
  service:
    name: systemd-networkd
    state: restarted
  become: yes
  listen: restart networkd
