---

- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - 'os_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml'
        - 'os_{{ ansible_distribution }}.yml'
        - 'os_{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: dpkg arch
  shell: dpkg --print-architecture
  register: dpkg_architecture

- name: set deb_arch
  set_fact:
    deb_arch: '{{ dpkg_architecture.stdout }}'

- name: show custom variables
  debug:
    var: '{{ item }}'
  loop:
    - deb_arch
    - apt_codename
