---
- name: add repository key
  get_url:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    dest: /etc/apt/trusted.gpg.d/google-chrome.asc
    mode: u=rw,g=r,o=r
    force: true
  become: yes

- name: add repository
  apt_repository:
    repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/trusted.gpg.d/google-chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  become: yes

- name: install
  package:
    name:
      - google-chrome-stable
    state: present
  become: yes
