---
- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: yes

- name: Allow outgoing connections
  community.general.ufw:
    policy: allow
    direction: outgoing
  become: yes

- name: Reject incoming connections
  community.general.ufw:
    policy: reject
    direction: incoming
  become: yes

- name: Deny all access to port 53
  community.general.ufw:
    rule: deny
    port: '53'
    insert: 0
    insert_relative_to: "last-ipv4"
  become: yes

- name: Allow access to resolvd extra listener
  community.general.ufw:
    rule: allow
    dest: '{{ resolvd_docker_listener }}'
    port: '53'
    proto: any
    insert: 0
    insert_relative_to: "first-ipv4"
  become: yes

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details.
- name: Rate-limit SSH connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: yes

# Allow OpenSSH.
- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: yes
