- name: Group for shared linuxbrew
  ansible.builtin.group:
    name: linuxbrew
  become: yes

- name: Ensure "{{ ansible_user_id }}" has access to linuxbrew group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - linuxbrew
    append: yes
  become: yes

- name: User for Illya Kysil
  ansible.builtin.user:
    name: ikysil
    shell: /bin/bash
    groups:
      - adm
      - docker
      - linuxbrew
      # - rust-cargo
      - scanner
      - sudo
      - systemd-journal
      - vboxusers
    append: yes
  become: yes
