---
- name: Base
  hosts: all
  roles:
    - os-vars
    - grub
    - nosnap
    - sysctl
    - clitools
    - linuxbrew
    - systemd
    - ufw
    - logrotate
    - docker-engine
    - openvpn3
    - users
  vars_files:
    - ../vars/global.yml
