---
- name: Graphical desktop stuff
  hosts: all
  roles:
    - bitwarden
    - clitools
    - keepassxc
    - nosnap
    - obs_studio
    - skype
    - sysctl
    - viber
    - vuescan
    - zoom
  vars_files:
    - ../vars/global.yml
