---
# A home computer
#
- import_playbook: base.yml
- import_playbook: desktop.yml

- name: Home
  hosts: all
  vars:
    - firewalld_zone: home
    - firewalld_enabled_services:
        - ssh

  roles:
    - github-cli
    - gitkraken
    - goland
    - slack

  tasks:
    # Log when we last ran
    - name: log run date to file
      copy:
        dest: /etc/buildinfo
        content: "{{ ansible_date_time.iso8601 }}"
        mode: u=rw,g=r,o=r
      become: yes

  vars_files:
    - ../vars/global.yml
    - ../vars/home.yml
